r"""Liquid Linear Units variants: input-adaptive linear transformations.

Each variant replaces a standard :class:`~nn.Linear` with a core path plus an
input-conditioned low-rank (or full) update generated by a hypernetwork.

The adaptive path is zero-initialised so the layer behaves as a
normal linear layer at step 1 (identity initialisation).

Available variants:

* :class:`LiquidLinear` - full per-example weight matrix (memory intensive).
* :class:`Rank1LiquidLN` - rank-1 outer-product update (lightweight).
* :class:`RankRLiquidLN` - rank-:math:`R` outer-product sum (best efficiency/expressivity).
* :class:`StableLiquidLN` - production variant with MLP hypernetwork and factor normalisation.
* :class:`SharedMomentumLiquidLN` - rank-:math:`R` EMA momentum, shared across batch.
* :class:`BatchMomentumLiquidLN` - rank-:math:`R` EMA momentum, per-batch-element.

"""

from typing import Optional

import torch
import torch.nn as nn
import torch.nn.functional as F

DEVICE = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# Helpers

_VALID_ACTIVATIONS = frozenset({"tanh", "norm", "rmsnorm", "none"})


def _activate(t: torch.Tensor, mode: str, eps: float = 1e-6) -> torch.Tensor:
    r"""_activate(t, mode, eps=1e-6) -> Tensor

    Apply one of the supported factor activations or normalisations.

    Args:
        t (Tensor): input tensor.
        mode (str): activation mode.  One of ``"tanh"``, ``"norm"``,
            ``"rmsnorm"``, or ``"none"``.
        eps (float): epsilon for numerical stability in ``"norm"`` and
            ``"rmsnorm"``.  Default: ``1e-6``.

    Returns:
        Tensor: activated tensor of the same shape as *t*.
    """
    if mode == "none":
        return t
    if mode == "tanh":
        return torch.tanh(t)
    if mode == "norm":
        return F.normalize(t, dim=-1, p=2, eps=eps)
    if mode == "rmsnorm":
        return F.rms_norm(t, (t.shape[-1],), eps=eps)
    raise ValueError(
        f"Unknown factor_activation '{mode}'; expected one of {sorted(_VALID_ACTIVATIONS)}"
    )


def _small_init(module: nn.Module, gain: float = 0.02) -> None:
    r"""_small_init(module, gain=0.02) -> None

    Apply Xavier uniform initialisation with a small gain.

    Linear layers are initialised with :func:`~torch.nn.init.xavier_uniform_`
    using *gain*; biases (if present) are zeroed.

    Args:
        module (nn.Module): a module (only :class:`~nn.Linear` is handled).
        gain (float): scaling gain.  Default: ``0.02``.
    """
    if isinstance(module, nn.Linear):
        nn.init.xavier_uniform_(module.weight, gain=gain)
        if module.bias is not None:
            nn.init.zeros_(module.bias)


def _last_linear(module: nn.Module) -> Optional[nn.Linear]:
    r"""_last_linear(module) -> nn.Linear or None

    Return the last :class:`~nn.Linear` in a module or :class:`~nn.Sequential`.

    Args:
        module (nn.Module): a module, possibly :class:`~nn.Sequential`.

    Returns:
        nn.Linear or None: the last linear layer, or ``None`` if the
        module is an empty :class:`~nn.Sequential` or does not end with
        a linear layer.
    """
    if isinstance(module, nn.Sequential):
        if len(module) == 0:
            return None
        module = module[-1]
    return module if isinstance(module, nn.Linear) else None


def _zero_out_last(module: nn.Module) -> None:
    r"""_zero_out_last(module) -> None

    Zero the weights and bias of the last :class:`~nn.Linear` in a chain.

    Respects :class:`~nn.Sequential` -- only the final layer is zeroed so that
    earlier layers can keep a standard init and receive gradient from step 1.

    .. note::
       This function zeros the *entire* output, which is correct for
       non-factored outputs (e.g. full weight matrix in :class:`LiquidLinear`).
       For factored rank outputs use :func:`_zero_b_section` instead so that
       the a-factors remain active for gradient flow.

    Args:
        module (nn.Module): a module or :class:`~nn.Sequential` whose last
            linear layer is zeroed.
    """
    last = _last_linear(module)
    if last is not None:
        nn.init.zeros_(last.weight)
        if last.bias is not None:
            nn.init.zeros_(last.bias)


def _zero_b_section(module: nn.Module, b_start: int) -> None:
    r"""_zero_b_section(module, b_start) -> None

    Zero the **b-section** rows (``[b_start:]``) of the last linear layer.

    The a-section (``[:b_start]``) keeps its previous init.  This partial
    zero-init ensures that at step 1:

    * the adaptive output is zero (because b-factors are zero), *yet*
    * gradients flow into the hypernetwork (because a-factors are non-zero).

    The a-section (``[:b_start]``) should have non-zero weights (from a prior
    init call such as :func:`_small_init`) so gradient flows through the
    hypernetwork.  The bias is zeroed independently here.

    Args:
        module (nn.Module): a module or :class:`~nn.Sequential` whose last
            linear layer is modified.
        b_start (int): row index where the b-section begins.
    """
    last = _last_linear(module)
    if last is not None:
        with torch.no_grad():
            last.weight.data[b_start:].zero_()
            # Zero entire bias (shared across a/b, a-section still fires via W_a@h).
            if last.bias is not None:
                last.bias.data.zero_()


# _FreezeMixin: shared freeze_core / freeze_hypernetwork


class _FreezeMixin:
    r"""Mixin providing ``freeze_core`` and ``freeze_hypernetwork``.

    Subclasses MUST have a :attr:`linear_core` attribute (a module whose
    parameters delimit the "core" from the "adaptive path").
    """

    linear_core: nn.Linear

    def freeze_core(self) -> None:
        r"""freeze_core() -> None

        Freeze all parameters of the core linear layer.
        Only the adaptive path (hypernetwork, scale, and dynamic bias)
        remains trainable.
        """
        for p in self.linear_core.parameters():
            p.requires_grad = False

    def freeze_hypernetwork(self) -> None:
        r"""freeze_hypernetwork() -> None

        Freeze all parameters *except* those of the core linear layer.
        Only :attr:`linear_core` remains trainable.
        """
        core_ids = {id(p) for p in self.linear_core.parameters()}
        assert isinstance(self, nn.Module)
        for p in self.parameters():
            if id(p) not in core_ids:
                p.requires_grad = False


# LiquidLinear: full per‑example weight matrix


class LiquidLinear(_FreezeMixin, nn.Module):
    """Input‑conditioned full weight matrix.

    Memory **O(B · O · I)**: use only for small dimensions.  The hypernetwork
    is a single linear layer; the generated full matrix is squashed with
    *factor_activation* (only ``"tanh"`` or ``"none"`` are well‑motivated here).

    Zero-initialised so the layer behaves as a plain ``nn.Linear`` at step 1.
    """

    def __init__(
        self,
        in_features: int,
        out_features: int,
        bias: bool = True,
        dynamic_bias: bool = True,
        factor_activation: str = "tanh",
        scale_init: float = 0.9,
        device: Optional[torch.device] = None,
        dtype: torch.dtype = torch.float32,
    ) -> None:
        r"""__init__(in_features, out_features, bias=True, dynamic_bias=True, factor_activation="tanh", scale_init=0.9, device=None, dtype=torch.float32) -> None

        Args:
            in_features (int): size of each input sample.
            out_features (int): size of each output sample.
            bias (bool): whether the core :class:`~nn.Linear` has a learnable bias.
                Default: ``True``.
            dynamic_bias (bool): if ``True``, an input-dependent bias from an
                auxiliary linear layer is added to the output.
                Default: ``True``.
            factor_activation (str): activation for the generated weight matrix.
                One of ``"tanh"``, ``"norm"``, ``"rmsnorm"``, or ``"none"``.
                Default: ``"tanh"``.
            scale_init (float): initial value of the per-channel scalar multiplier
                on the adaptive path.  Default: ``0.9``.
            device (torch.device, optional): the desired device of the parameters.
                Default: ``None``.
            dtype (torch.dtype): the desired data type of the parameters.
                Default: ``torch.float32``.
        """
        super().__init__()
        dev = device if device is not None else DEVICE

        self.in_features = in_features
        self.out_features = out_features
        self.factor_activation = factor_activation

        # Core weight (always active)
        self.linear_core = nn.Linear(in_features, out_features, bias=bias, device=dev, dtype=dtype)

        # Hypernetwork -> full out x in matrix
        self.hypernetwork = nn.Linear(
            in_features,
            out_features * in_features,
            bias=True,
            device=dev,
            dtype=dtype,
        )

        # Per-channel dial for adaptive path
        self.scale = nn.Parameter(torch.full((out_features,), scale_init, device=dev, dtype=dtype))

        # Optional input‑dependent bias
        self.bias_dynamic: Optional[nn.Linear] = (
            nn.Linear(in_features, out_features, bias=True, device=dev, dtype=dtype)
            if dynamic_bias
            else None
        )

        self._init_weights()

    # Init

    def _init_weights(self) -> None:
        r"""_init_weights() -> None

        Initialise the hypernetwork and dynamic bias (if present) with
        small gains, then zero the output layer so the adaptive path
        contributes nothing at step 1.
        """
        # Zero hypernetwork -> adaptive path = 0
        _small_init(self.hypernetwork)
        _zero_out_last(self.hypernetwork)

        if self.bias_dynamic is not None:
            _small_init(self.bias_dynamic)
            _zero_out_last(self.bias_dynamic)

    # Forward

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        r"""forward(x) -> Tensor

        Args:
            x (Tensor): input tensor of shape ``(..., in_features)``.

        Returns:
            Tensor: output tensor of shape ``(..., out_features)`` computed as
            :math:`\text{core}(x) + \text{scale} \odot (W(x) \cdot x)`, where
            :math:`W(x)` is the input-conditioned full weight matrix.
        """
        core_out = self.linear_core(x)  # (..., O)

        # Dynamic matrix, activated
        W_raw = self.hypernetwork(x)  # (..., O*I)
        W = _activate(W_raw, self.factor_activation)
        W = W.reshape(*x.shape[:-1], self.out_features, self.in_features)  # (..., O, I)

        # delta_W = W @ x
        adaptive = torch.matmul(W, x.unsqueeze(-1)).squeeze(-1)  # (..., O)

        # Scale adaptive path, add bias
        out = core_out + adaptive * self.scale

        if self.bias_dynamic is not None:
            out = out + self.bias_dynamic(x)

        return out

    # Utilities

    def extra_repr(self) -> str:
        return f"in={self.in_features}, out={self.out_features}, act={self.factor_activation}"


# Rank1LiquidLN: rank‑1 adaptive factors


class Rank1LiquidLN(_FreezeMixin, nn.Module):
    """Input‑conditioned rank‑1 update (lightweight).

    The hypernetwork outputs a single pair of vectors :math:`a \\in \\mathbb{R}^O`,
    :math:`b \\in \\mathbb{R}^I` which are then activated (default ``"norm"``).
    The effective dynamic update is :math:`\\Delta W = a \\otimes b`.

    Zero-initialised so :math:`\\Delta W = 0` at step 1.
    """

    def __init__(
        self,
        in_features: int,
        out_features: int,
        bias: bool = True,
        dynamic_bias: bool = False,
        factor_activation: str = "norm",
        scale_init: float = 0.9,
        normalize_input: bool = False,
        device: Optional[torch.device] = None,
        dtype: torch.dtype = torch.float32,
    ) -> None:
        r"""__init__(in_features, out_features, bias=True, dynamic_bias=False, factor_activation="norm", scale_init=0.5, normalize_input=False, device=None, dtype=torch.float32) -> None

        Args:
            in_features (int): size of each input sample.
            out_features (int): size of each output sample.
            bias (bool): whether the core :class:`~nn.Linear` has a learnable bias.
                Default: ``True``.
            dynamic_bias (bool): if ``True``, an input-dependent bias from an
                auxiliary linear layer is added to the output.
                Default: ``False``.
            factor_activation (str): activation for the factor vectors :math:`a, b`.
                One of ``"tanh"``, ``"norm"``, ``"rmsnorm"``, or ``"none"``.
                ``"norm"`` is recommended.  Default: ``"norm"``.
            scale_init (float): initial value of the per-channel scalar multiplier
                on the adaptive path.  Default: ``0.9``.
            normalize_input (bool): if ``True``, apply RMSNorm to the input before
                feeding it to the hypernetwork.  Default: ``False``.
            device (torch.device, optional): the desired device of the parameters.
                Default: ``None``.
            dtype (torch.dtype): the desired data type of the parameters.
                Default: ``torch.float32``.
        """
        super().__init__()
        dev = device if device is not None else DEVICE

        self.in_features = in_features
        self.out_features = out_features
        self.factor_activation = factor_activation
        self.normalize_input = normalize_input

        self.linear_core = nn.Linear(in_features, out_features, bias=bias, device=dev, dtype=dtype)

        # Single hypernetwork -> a (O) + b (I)
        self.hypernetwork = nn.Linear(
            in_features,
            out_features + in_features,
            bias=True,
            device=dev,
            dtype=dtype,
        )

        self.scale = nn.Parameter(torch.full((out_features,), scale_init, device=dev, dtype=dtype))

        self.bias_dynamic: Optional[nn.Linear] = (
            nn.Linear(in_features, out_features, bias=True, device=dev, dtype=dtype)
            if dynamic_bias
            else None
        )

        self._init_weights()

    def _init_weights(self) -> None:
        r"""_init_weights() -> None

        Initialise the hypernetwork with a small gain, then zero the
        b‑section of its output layer so that :math:`\Delta W = 0` at
        step 1 while gradient still flows through the a‑factors.
        """
        _small_init(self.hypernetwork)
        # Zero b-section only; a keeps gradient flowing
        _zero_b_section(self.hypernetwork, self.out_features)

        if self.bias_dynamic is not None:
            _small_init(self.bias_dynamic)
            _zero_out_last(self.bias_dynamic)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        r"""forward(x) -> Tensor

        Args:
            x (Tensor): input tensor of shape ``(..., in_features)``.

        Returns:
            Tensor: output tensor of shape ``(..., out_features)`` computed as
            :math:`\text{core}(x) + \text{scale} \odot a \, (b \cdot x)`, where
            :math:`a \in \mathbb{R}^O, b \in \mathbb{R}^I` are the
            input-conditioned rank-1 factors.
        """

        # RMSNorm for magnitude invariance
        h_in = F.rms_norm(x, (self.in_features,)) if self.normalize_input else x

        raw = self.hypernetwork(h_in)  # (..., O + I)

        a = _activate(raw[..., : self.out_features], self.factor_activation)
        b = _activate(raw[..., self.out_features :], self.factor_activation)

        # delta_W x = a(b·x) so no full matrix needed (avoid unnecessary memory allocation)
        dot = torch.sum(x * b, dim=-1, keepdim=True)  # (..., 1)
        adaptive = a * dot  # (..., O)

        out = self.linear_core(x) + adaptive * self.scale

        if self.bias_dynamic is not None:
            out = out + self.bias_dynamic(x)

        return out

    def extra_repr(self) -> str:
        return (
            f"in={self.in_features}, out={self.out_features}, "
            f"act={self.factor_activation}, norm_input={self.normalize_input}"
        )


# RankRLiquidLN - rank-R adaptive factors (best efficiency / expressivity)


class RankRLiquidLN(_FreezeMixin, nn.Module):
    """Input‑conditioned rank‑R update.

    Generates :math:`R` pairs of factors :math:`\\{a_r, b_r\\}`.  The dynamic
    update is :math:`\\Delta W = \\sum_{r=1}^R \\alpha_r \\, a_r \\otimes b_r`
    where :math:`\\alpha_r` = ``rank_scale[r]``.

    The hypernetwork can be a plain Linear (faster) or a 2‑layer MLP with
    SiLU (more expressive) by setting *nonlinear_hypernet*.
    """

    def __init__(
        self,
        in_features: int,
        out_features: int,
        rank: int = 1,
        bias: bool = True,
        dynamic_bias: bool = False,
        factor_activation: str = "norm",
        scale_init: float = 0.5,
        normalize_input: bool = False,
        nonlinear_hypernet: bool = False,
        hyper_hidden_dim: Optional[int] = None,
        device: Optional[torch.device] = None,
        dtype: torch.dtype = torch.float32,
    ) -> None:
        r"""__init__(in_features, out_features, rank=1, bias=True, dynamic_bias=False, factor_activation="norm", scale_init=0.5, normalize_input=False, nonlinear_hypernet=False, hyper_hidden_dim=None, device=None, dtype=torch.float32) -> None

        Args:
            in_features (int): size of each input sample.
            out_features (int): size of each output sample.
            rank (int): number of factor pairs :math:`(a_r, b_r)`.  Default: ``1``.
            bias (bool): whether the core :class:`~nn.Linear` has a learnable bias.
                Default: ``True``.
            dynamic_bias (bool): if ``True``, an input-dependent bias from an
                auxiliary linear layer is added to the output.
                Default: ``False``.
            factor_activation (str): activation for the factor vectors.
                One of ``"tanh"``, ``"norm"``, ``"rmsnorm"``, or ``"none"``.
                Default: ``"norm"``.
            scale_init (float): initial value of the per-channel scalar multiplier
                on the adaptive path.  Default: ``0.5``.
            normalize_input (bool): if ``True``, apply RMSNorm to the input before
                feeding it to the hypernetwork.  Default: ``False``.
            nonlinear_hypernet (bool): if ``True``, use a 2-layer MLP (SiLU)
                instead of a single linear layer for the hypernetwork.
                Default: ``False``.
            hyper_hidden_dim (int, optional): hidden dimension of the MLP
                hypernetwork.  Ignored when *nonlinear_hypernet* is ``False``.
                Default: ``None`` (``max(in_features // 4, rank * 16)``).
            device (torch.device, optional): the desired device of the parameters.
                Default: ``None``.
            dtype (torch.dtype): the desired data type of the parameters.
                Default: ``torch.float32``.
        """
        super().__init__()
        if rank < 1:
            raise ValueError(f"rank must be >= 1, got {rank}")
        dev = device if device is not None else DEVICE

        self.in_features = in_features
        self.out_features = out_features
        self.rank = rank
        self.factor_activation = factor_activation
        self.normalize_input = normalize_input

        self.linear_core = nn.Linear(in_features, out_features, bias=bias, device=dev, dtype=dtype)

        # Hypernetwork: linear or 2-layer MLP
        hyper_out_dim = rank * (out_features + in_features)
        if nonlinear_hypernet:
            hidden = hyper_hidden_dim or max(in_features // 4, rank * 16)
            self.hypernetwork: nn.Module = nn.Sequential(
                nn.Linear(in_features, hidden, device=dev, dtype=dtype),
                nn.SiLU(),
                nn.Linear(hidden, hyper_out_dim, device=dev, dtype=dtype),
            )
        else:
            self.hypernetwork = nn.Linear(
                in_features, hyper_out_dim, bias=True, device=dev, dtype=dtype
            )

        self.scale = nn.Parameter(torch.full((out_features,), scale_init, device=dev, dtype=dtype))
        self.rank_scale = nn.Parameter(torch.full((rank,), 1.0, device=dev, dtype=dtype))

        self.bias_dynamic: Optional[nn.Linear] = (
            nn.Linear(in_features, out_features, bias=True, device=dev, dtype=dtype)
            if dynamic_bias
            else None
        )

        self._init_weights()

    def _init_weights(self) -> None:
        r"""_init_weights() -> None

        Initialise hypernetwork layers with a small gain (avoids tanh
        saturation when ``factor_activation="tanh"``), then zero the
        b‑section of the output layer so the adaptive path produces
        zero at step 1 while a‑factors keep gradient flowing.
        """
        if isinstance(self.hypernetwork, nn.Sequential):
            for m in self.hypernetwork:
                _small_init(m)
        else:
            _small_init(self.hypernetwork)

        # Zero b-section; a-weights keep small init (avoid tanh saturation).
        _zero_b_section(self.hypernetwork, self.rank * self.out_features)

        if self.bias_dynamic is not None:
            _small_init(self.bias_dynamic)
            _zero_out_last(self.bias_dynamic)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        r"""forward(x) -> Tensor

        Args:
            x (Tensor): input tensor of shape ``(..., in_features)``.

        Returns:
            Tensor: output tensor of shape ``(..., out_features)`` computed as
            :math:`\text{core}(x) + \text{scale} \odot \sum_{r=1}^R \alpha_r \,
            a_r \, (b_r \cdot x)`, where :math:`\alpha_r` = ``rank_scale[r]``.
        """
        h_in = F.rms_norm(x, (self.in_features,)) if self.normalize_input else x
        raw = self.hypernetwork(h_in)

        split = self.rank * self.out_features
        a_raw = raw[..., :split].reshape(*x.shape[:-1], self.rank, self.out_features)
        b_raw = raw[..., split:].reshape(*x.shape[:-1], self.rank, self.in_features)

        a = _activate(a_raw, self.factor_activation)
        b = _activate(b_raw, self.factor_activation)

        # Dot products: b_r @ x -> (..., rank)
        dot = torch.matmul(b, x.unsqueeze(-1)).squeeze(-1)  # (..., rank)
        dot = dot * self.rank_scale

        # Weighted sum over rank
        adaptive = torch.matmul(dot.unsqueeze(-2), a).squeeze(-2)  # (..., O)

        out = self.linear_core(x) + adaptive * self.scale

        if self.bias_dynamic is not None:
            out = out + self.bias_dynamic(x)

        return out

    def extra_repr(self) -> str:
        nonlinear = isinstance(self.hypernetwork, nn.Sequential)
        return (
            f"in={self.in_features}, out={self.out_features}, rank={self.rank}, "
            f"act={self.factor_activation}, norm_input={self.normalize_input}, "
            f"nonlinear_hypernet={nonlinear}"
        )


# StableLiquidLN: nonlinear hypernet + factor normalisation + cond support


class StableLiquidLN(_FreezeMixin, nn.Module):
    """Production‑oriented variant with nonlinear hypernetwork and normalised factors.

    The hypernetwork is a 2‑layer MLP (SiLU).  Generated factors are
    activated (default L2‑norm) and summed over rank.  Unlike simpler variants,
    this module accepts an optional separate *cond* tensor for conditioning.

    Zero-initialised so the adaptive path contributes nothing at step 1.
    """

    def __init__(
        self,
        in_features: int,
        out_features: int,
        rank: int = 4,
        hyper_hidden_dim: Optional[int] = None,
        bias: bool = True,
        dynamic_bias: bool = False,
        factor_activation: str = "norm",
        scale_init: float = 0.01,
        normalize_input: bool = True,
        device: Optional[torch.device] = None,
        dtype: torch.dtype = torch.float32,
    ) -> None:
        r"""__init__(in_features, out_features, rank=4, hyper_hidden_dim=None, bias=True, dynamic_bias=False, factor_activation="norm", scale_init=0.01, normalize_input=True, device=None, dtype=torch.float32) -> None

        Args:
            in_features (int): size of each input sample.
            out_features (int): size of each output sample.
            rank (int): number of factor pairs :math:`(a_r, b_r)`.  Default: ``4``.
            hyper_hidden_dim (int, optional): hidden dimension of the MLP
                hypernetwork.  Default: ``None`` (``max(in_features // 4, rank * 16)``).
            bias (bool): whether the core :class:`~nn.Linear` has a learnable bias.
                Default: ``True``.
            dynamic_bias (bool): if ``True``, an input-dependent bias from an
                MLP is added to the output.  Default: ``False``.
            factor_activation (str): activation for the factor vectors.
                One of ``"tanh"``, ``"norm"``, ``"rmsnorm"``, or ``"none"``.
                Default: ``"norm"``.
            scale_init (float): initial value of the per-channel scalar multiplier
                on the adaptive path.  Default: ``0.01``.
            normalize_input (bool): if ``True``, apply RMSNorm to the conditioning
                input before the hypernetwork.  Default: ``True``.
            device (torch.device, optional): the desired device of the parameters.
                Default: ``None``.
            dtype (torch.dtype): the desired data type of the parameters.
                Default: ``torch.float32``.
        """
        super().__init__()
        if rank < 1:
            raise ValueError(f"rank must be >= 1, got {rank}")
        dev = device if device is not None else DEVICE

        self.in_features = in_features
        self.out_features = out_features
        self.rank = rank
        self.factor_activation = factor_activation
        self.normalize_input = normalize_input

        self.linear_core = nn.Linear(in_features, out_features, bias=bias, device=dev, dtype=dtype)

        # MLP hypernetwork
        hidden_dim = hyper_hidden_dim or max(in_features // 4, rank * 16)
        self.hypernetwork = nn.Sequential(
            nn.Linear(in_features, hidden_dim, device=dev, dtype=dtype),
            nn.SiLU(),
            nn.Linear(hidden_dim, rank * (out_features + in_features), device=dev, dtype=dtype),
        )

        # Scaling dial
        self.scale = nn.Parameter(torch.full((out_features,), scale_init, device=dev, dtype=dtype))
        self.rank_scale = nn.Parameter(torch.full((rank,), 1.0, device=dev, dtype=dtype))

        # Dynamic bias with MLP
        self.bias_dynamic: Optional[nn.Sequential] = (
            nn.Sequential(
                nn.Linear(in_features, hidden_dim, device=dev, dtype=dtype),
                nn.SiLU(),
                nn.Linear(hidden_dim, out_features, device=dev, dtype=dtype),
            )
            if dynamic_bias
            else None
        )

        self._init_weights()

    def _init_weights(self) -> None:
        r"""_init_weights() -> None

        Initialise MLP layers with a small gain (avoids tanh saturation
        when ``factor_activation="tanh"``), then zero the b-section of
        the output layer so the adaptive path produces zero at step 1
        while a-factors keep gradient flowing.

        The dynamic bias MLP (if present) is small-initialised and its
        final layer zeroed.
        """
        # Small init avoids tanh saturation when ``factor_activation="tanh"``.
        for m in self.hypernetwork:
            _small_init(m)

        # Zero b-section; a-factors keep gradient flowing
        _zero_b_section(self.hypernetwork, self.rank * self.out_features)

        if self.bias_dynamic is not None:
            for m in self.bias_dynamic[:-1]:
                _small_init(m)
            _zero_out_last(self.bias_dynamic)

    def forward(self, x: torch.Tensor, cond: Optional[torch.Tensor] = None) -> torch.Tensor:
        r"""forward(x, cond=None) -> Tensor

        Args:
            x (Tensor): input tensor of shape ``(..., in_features)``.
            cond (Tensor, optional): optional conditioning tensor.  When
            ``None``, *x* is used.  The conditioning drives the hypernetwork
            while *x* always goes through the core linear path.

        Returns:
            Tensor: output tensor of shape ``(..., out_features)`` with
            nonlinear hypernetwork and normalised rank-:math:`R` factors.
        """
        cond = cond if cond is not None else x

        # RMSNorm for magnitude invariance
        h_in = F.rms_norm(cond, (self.in_features,)) if self.normalize_input else cond

        core_out = self.linear_core(x)

        raw = self.hypernetwork(h_in)

        split = self.rank * self.out_features
        a_raw = raw[..., :split].reshape(*h_in.shape[:-1], self.rank, self.out_features)
        b_raw = raw[..., split:].reshape(*h_in.shape[:-1], self.rank, self.in_features)

        a = _activate(a_raw, self.factor_activation)
        b = _activate(b_raw, self.factor_activation)

        dot = torch.matmul(b, x.unsqueeze(-1)).squeeze(-1)  # (..., rank)
        dot = dot * self.rank_scale

        adaptive = torch.matmul(dot.unsqueeze(-2), a).squeeze(-2)  # (..., O)

        out = core_out + adaptive * self.scale

        if self.bias_dynamic is not None:
            out = out + self.bias_dynamic(cond)

        return out

    def extra_repr(self) -> str:
        return (
            f"in={self.in_features}, out={self.out_features}, rank={self.rank}, "
            f"act={self.factor_activation}, norm_input={self.normalize_input}"
        )


# SharedMomentumLiquidLN: rank-level momentum shared across batch


class SharedMomentumLiquidLN(_FreezeMixin, nn.Module):
    r"""Input-conditioned rank-:math:`R` update with exponential-moving-average momentum.

    Extends :class:`StableLiquidLN` with momentum over the generated factors.
    At each forward pass the raw hypernetwork outputs are blended into persistent
    buffers ``a_raw`` and ``b_raw`` via

    :math:`\mathtt{a\_raw} \gets \mathtt{a\_raw} \cdot \mathtt{decay\_rate}
    + a_{\text{raw}}^{\text{(new)}}`

    before activation and the rank-:math:`R` update. The momentum smooths
    factor transitions across time steps.

    **Shared (rank-level) momentum.** The raw factors from all batch elements
    are averaged before blending into the buffer, so the buffer has no batch
    dimension -- shape ``(rank, feat)``.  All samples share the same momentum
    state, which suits autoregressive teacher-forcing where the relevant
    dynamics are per-position, not per-sample.

    Zero-initialised so the adaptive path contributes nothing at step 1.
    """

    def __init__(
        self,
        in_features: int,
        out_features: int,
        decay_rate=0.4,
        rank: int = 4,
        hyper_hidden_dim: Optional[int] = None,
        bias: bool = True,
        dynamic_bias: bool = False,
        factor_activation: str = "norm",
        scale_init: float = 0.01,
        normalize_input: bool = True,
        device: Optional[torch.device] = None,
        dtype: torch.dtype = torch.float32,
    ) -> None:
        r"""__init__(in_features, out_features, decay_rate=0.4, rank=4, hyper_hidden_dim=None, bias=True, dynamic_bias=False, factor_activation="norm", scale_init=0.01, normalize_input=True, device=None, dtype=torch.float32) -> None

        Args:
            in_features (int): size of each input sample.
            out_features (int): size of each output sample.
            decay_rate (float): decay factor for the momentum buffers.
                Values close to ``1`` give longer memory.  Default: ``0.4``.
            rank (int): number of factor pairs :math:`(a_r, b_r)`.  Default: ``4``.
            hyper_hidden_dim (int, optional): hidden dimension of the MLP
                hypernetwork.  Default: ``None`` (``max(in_features // 4, rank * 16)``).
            bias (bool): whether the core :class:`~nn.Linear` has a learnable bias.
                Default: ``True``.
            dynamic_bias (bool): if ``True``, an input-dependent bias from an
                MLP is added to the output.  Default: ``False``.
            factor_activation (str): activation for the factor vectors.
                One of ``"tanh"``, ``"norm"``, ``"rmsnorm"``, or ``"none"``.
                Default: ``"norm"``.
            scale_init (float): initial value of the per-channel scalar multiplier
                on the adaptive path.  Default: ``0.01``.
            normalize_input (bool): if ``True``, apply RMSNorm to the conditioning
                input before the hypernetwork.  Default: ``True``.
            device (torch.device, optional): the desired device of the parameters.
                Default: ``None``.
            dtype (torch.dtype): the desired data type of the parameters.
                Default: ``torch.float32``.
        """
        super().__init__()
        if rank < 1:
            raise ValueError(f"rank must be >= 1, got {rank}")
        dev = device if device is not None else DEVICE

        self.in_features = in_features
        self.out_features = out_features
        self.rank = rank
        self.factor_activation = factor_activation
        self.normalize_input = normalize_input

        self.linear_core = nn.Linear(in_features, out_features, bias=bias, device=dev, dtype=dtype)

        self.decay_rate = decay_rate

        self.register_buffer(
            "a_raw", torch.zeros(rank, out_features, device=dev, dtype=dtype), persistent=True
        )
        self.register_buffer(
            "b_raw", torch.zeros(rank, in_features, device=dev, dtype=dtype), persistent=True
        )

        # MLP hypernetwork
        hidden_dim = hyper_hidden_dim or max(in_features // 4, rank * 16)
        self.hypernetwork = nn.Sequential(
            nn.Linear(in_features, hidden_dim, device=dev, dtype=dtype),
            nn.SiLU(),
            nn.Linear(hidden_dim, rank * (out_features + in_features), device=dev, dtype=dtype),
        )

        # Scaling dial
        self.scale = nn.Parameter(torch.full((out_features,), scale_init, device=dev, dtype=dtype))
        self.rank_scale = nn.Parameter(torch.full((rank,), 1.0, device=dev, dtype=dtype))

        # Dynamic bias with MLP
        self.bias_dynamic: Optional[nn.Sequential] = (
            nn.Sequential(
                nn.Linear(in_features, hidden_dim, device=dev, dtype=dtype),
                nn.SiLU(),
                nn.Linear(hidden_dim, out_features, device=dev, dtype=dtype),
            )
            if dynamic_bias
            else None
        )

        self._init_weights()

    def _init_weights(self) -> None:
        r"""_init_weights() -> None

        Initialise MLP layers with a small gain (avoids tanh saturation
        when ``factor_activation="tanh"``), then zero the b-section of
        the output layer so the adaptive path produces zero at step 1
        while a-factors keep gradient flowing.

        The dynamic bias MLP (if present) is small-initialised and its
        final layer zeroed.
        """

        # Small init avoids tanh saturation when ``factor_activation="tanh"``.
        for m in self.hypernetwork:
            _small_init(m)

        # Zero b-section; a-factors keep gradient flowing
        _zero_b_section(self.hypernetwork, self.rank * self.out_features)

        if self.bias_dynamic is not None:
            for m in self.bias_dynamic[:-1]:
                _small_init(m)
            _zero_out_last(self.bias_dynamic)

    def forward(self, x: torch.Tensor, cond: Optional[torch.Tensor] = None) -> torch.Tensor:
        r"""forward(x, cond=None) -> Tensor

        Args:
            x (Tensor): input tensor of shape ``(..., in_features)``.
            cond (Tensor, optional): optional conditioning tensor.  When
                ``None``, *x* is used.  The conditioning drives the hypernetwork
                while *x* always goes through the core linear path.

        Returns:
            Tensor: output tensor of shape ``(..., out_features)`` with
            momentum-smoothed rank-:math:`R` adaptive update.
        """

        cond = cond if cond is not None else x

        # RMSNorm for magnitude invariance
        h_in = F.rms_norm(cond, (self.in_features,)) if self.normalize_input else cond

        core_out = self.linear_core(x)

        raw = self.hypernetwork(h_in)

        split = self.rank * self.out_features

        a_new = raw[..., :split].reshape(*h_in.shape[:-1], self.rank, self.out_features)
        b_new = raw[..., split:].reshape(*h_in.shape[:-1], self.rank, self.in_features)

        # Rank-level momentum: mean over all batch dims → (rank, feat)
        a_mean = a_new.mean(dim=tuple(range(a_new.ndim - 2)))
        b_mean = b_new.mean(dim=tuple(range(b_new.ndim - 2)))
        self.a_raw = self.a_raw * self.decay_rate + a_mean
        self.b_raw = self.b_raw * self.decay_rate + b_mean

        # Expand back to match batch
        a = _activate(self.a_raw.expand_as(a_new), self.factor_activation)
        b = _activate(self.b_raw.expand_as(b_new), self.factor_activation)

        dot = torch.matmul(b, x.unsqueeze(-1)).squeeze(-1)  # (..., rank)
        dot = dot * self.rank_scale

        adaptive = torch.matmul(dot.unsqueeze(-2), a).squeeze(-2)  # (..., O)

        out = core_out + adaptive * self.scale

        if self.bias_dynamic is not None:
            out = out + self.bias_dynamic(cond)

        return out

    def extra_repr(self) -> str:
        return (
            f"in={self.in_features}, out={self.out_features}, rank={self.rank}, "
            f"act={self.factor_activation}, norm_input={self.normalize_input}"
        )


# BatchMomentumLiquidLN: per-batch-element momentum


class BatchMomentumLiquidLN(_FreezeMixin, nn.Module):
    r"""Input-conditioned rank-:math:`R` update with per-batch-element momentum.

    Like :class:`SharedMomentumLiquidLN` but the momentum is tracked separately
    for each element in the batch dimension.  The raw buffers have shape
    ``(*batch, rank, feat)`` -- the batch dimensions are included and each
    :math:`(b_1, \dots, b_n)` slice has its own state.

    Because the buffer shape depends on the input, a runtime guard detects
    shape/device/dtype mismatches and re-initialises the buffer when needed
    (e.g. on batch-size changes).  This makes it slightly heavier than
    :class:`SharedMomentumLiquidLN` but necessary when per-sample momentum
    dynamics are required.

    Zero-initialised so the adaptive path contributes nothing at step 1.
    """

    def __init__(
        self,
        in_features: int,
        out_features: int,
        decay_rate=0.4,
        rank: int = 4,
        hyper_hidden_dim: Optional[int] = None,
        bias: bool = True,
        dynamic_bias: bool = False,
        factor_activation: str = "norm",
        scale_init: float = 0.01,
        normalize_input: bool = True,
        device: Optional[torch.device] = None,
        dtype: torch.dtype = torch.float32,
    ) -> None:
        r"""__init__(in_features, out_features, decay_rate=0.4, rank=4, hyper_hidden_dim=None, bias=True, dynamic_bias=False, factor_activation="norm", scale_init=0.01, normalize_input=True, device=None, dtype=torch.float32) -> None

        Args:
            in_features (int): size of each input sample.
            out_features (int): size of each output sample.
            decay_rate (float): decay factor for the momentum buffers.
                Values close to ``1`` give longer memory.  Default: ``0.4``.
            rank (int): number of factor pairs :math:`(a_r, b_r)`.  Default: ``4``.
            hyper_hidden_dim (int, optional): hidden dimension of the MLP
                hypernetwork.  Default: ``None`` (``max(in_features // 4, rank * 16)``).
            bias (bool): whether the core :class:`~nn.Linear` has a learnable bias.
                Default: ``True``.
            dynamic_bias (bool): if ``True``, an input-dependent bias from an
                MLP is added to the output.  Default: ``False``.
            factor_activation (str): activation for the factor vectors.
                One of ``"tanh"``, ``"norm"``, ``"rmsnorm"``, or ``"none"``.
                Default: ``"norm"``.
            scale_init (float): initial value of the per-channel scalar multiplier
                on the adaptive path.  Default: ``0.01``.
            normalize_input (bool): if ``True``, apply RMSNorm to the conditioning
                input before the hypernetwork.  Default: ``True``.
            device (torch.device, optional): the desired device of the parameters.
                Default: ``None``.
            dtype (torch.dtype): the desired data type of the parameters.
                Default: ``torch.float32``.
        """
        super().__init__()
        if rank < 1:
            raise ValueError(f"rank must be >= 1, got {rank}")
        dev = device if device is not None else DEVICE

        self.in_features = in_features
        self.out_features = out_features
        self.rank = rank
        self.factor_activation = factor_activation
        self.normalize_input = normalize_input

        self.linear_core = nn.Linear(in_features, out_features, bias=bias, device=dev, dtype=dtype)

        self.decay_rate = decay_rate

        # Placeholder buffer; real shape is set on first forward via the guard
        self.register_buffer(
            "a_raw", torch.zeros(1, rank, out_features, device=dev, dtype=dtype), persistent=True
        )
        self.register_buffer(
            "b_raw", torch.zeros(1, rank, in_features, device=dev, dtype=dtype), persistent=True
        )

        # MLP hypernetwork
        hidden_dim = hyper_hidden_dim or max(in_features // 4, rank * 16)
        self.hypernetwork = nn.Sequential(
            nn.Linear(in_features, hidden_dim, device=dev, dtype=dtype),
            nn.SiLU(),
            nn.Linear(hidden_dim, rank * (out_features + in_features), device=dev, dtype=dtype),
        )

        # Scaling dial
        self.scale = nn.Parameter(torch.full((out_features,), scale_init, device=dev, dtype=dtype))
        self.rank_scale = nn.Parameter(torch.full((rank,), 1.0, device=dev, dtype=dtype))

        # Dynamic bias with MLP
        self.bias_dynamic: Optional[nn.Sequential] = (
            nn.Sequential(
                nn.Linear(in_features, hidden_dim, device=dev, dtype=dtype),
                nn.SiLU(),
                nn.Linear(hidden_dim, out_features, device=dev, dtype=dtype),
            )
            if dynamic_bias
            else None
        )

        self._init_weights()

    def _init_weights(self) -> None:
        r"""_init_weights() -> None

        Initialise MLP layers with a small gain (avoids tanh saturation
        when ``factor_activation="tanh"``), then zero the b-section of
        the output layer so the adaptive path produces zero at step 1
        while a-factors keep gradient flowing.

        The dynamic bias MLP (if present) is small-initialised and its
        final layer zeroed.
        """

        # Small init avoids tanh saturation when ``factor_activation="tanh"``.
        for m in self.hypernetwork:
            _small_init(m)

        # Zero b-section; a-factors keep gradient flowing
        _zero_b_section(self.hypernetwork, self.rank * self.out_features)

        if self.bias_dynamic is not None:
            for m in self.bias_dynamic[:-1]:
                _small_init(m)
            _zero_out_last(self.bias_dynamic)

    def forward(self, x: torch.Tensor, cond: Optional[torch.Tensor] = None) -> torch.Tensor:
        r"""forward(x, cond=None) -> Tensor

        Args:
            x (Tensor): input tensor of shape ``(..., in_features)``.
            cond (Tensor, optional): optional conditioning tensor.  When
                ``None``, *x* is used.  The conditioning drives the hypernetwork
                while *x* always goes through the core linear path.

        Returns:
            Tensor: output tensor of shape ``(..., out_features)`` with
            momentum-smoothed rank-:math:`R` adaptive update.
        """

        cond = cond if cond is not None else x

        # RMSNorm for magnitude invariance
        h_in = F.rms_norm(cond, (self.in_features,)) if self.normalize_input else cond

        core_out = self.linear_core(x)

        raw = self.hypernetwork(h_in)

        split = self.rank * self.out_features

        a_new = raw[..., :split].reshape(*h_in.shape[:-1], self.rank, self.out_features)
        b_new = raw[..., split:].reshape(*h_in.shape[:-1], self.rank, self.in_features)

        # Re-init buffers if shape/device/dtype mismatch
        if (
            self.a_raw.shape != a_new.shape
            or self.a_raw.device != x.device
            or self.a_raw.dtype != x.dtype
        ):
            self.a_raw = torch.zeros(a_new.shape, device=x.device, dtype=x.dtype)
        if (
            self.b_raw.shape != b_new.shape
            or self.b_raw.device != x.device
            or self.b_raw.dtype != x.dtype
        ):
            self.b_raw = torch.zeros(b_new.shape, device=x.device, dtype=x.dtype)

        # Per-batch-element EMA
        self.a_raw = self.a_raw * self.decay_rate + a_new
        self.b_raw = self.b_raw * self.decay_rate + b_new

        a = _activate(self.a_raw, self.factor_activation)
        b = _activate(self.b_raw, self.factor_activation)

        dot = torch.matmul(b, x.unsqueeze(-1)).squeeze(-1)  # (..., rank)
        dot = dot * self.rank_scale

        adaptive = torch.matmul(dot.unsqueeze(-2), a).squeeze(-2)  # (..., O)

        out = core_out + adaptive * self.scale

        if self.bias_dynamic is not None:
            out = out + self.bias_dynamic(cond)

        return out

    def extra_repr(self) -> str:
        return (
            f"in={self.in_features}, out={self.out_features}, rank={self.rank}, "
            f"act={self.factor_activation}, norm_input={self.normalize_input}"
        )
