r"""CrossAttnLoraLN: LoRA-style learned low-rank factors refined by cross-attention.

The two low-rank factors are stored as plain learned parameters -- exactly like
the ``A`` / ``B`` pair of a normal LoRA adapter (or ``U`` / ``V`` under the SVD
parameterization) -- instead of being generated by an input-conditioned
hypernetwork.

The novelty is the *update rule* for those factors. Rather than a per-token
hypernetwork, the factors act as a small set of **target tokens** that attend,
via a ``torch.nn.TransformerDecoderLayer`` cross-attention, to the **source
sequence** (the conditioning ``cond`` tensor, which defaults to ``x``). The
sequence supplies keys and values; the two factor matrices supply the queries
(after being projected into a shared attention space). Because the factor
matrices live in two different spaces (``out_features`` for ``A``/``U`` and
``in_features`` for ``B``/``V``), each is projected into the common
``attn_dim`` attention space before attention and projected back afterwards --
the "necessary adjustment" for the mismatched dimensions. A residual connection
(zero-initialised so the adaptive path contributes nothing at step 1) lets the
factors be refined per example as a function of the sequence.

This keeps the same external contract as :class:`~llu.models.llns.stable_liquid.StableLiquidLN`:
a ``linear_core`` plus an additive adaptive path, optional dynamic bias,
optional ``cond``, ``normalize_input`` and ``factor_activation``, and both
``lora`` and ``svd`` parameterizations.
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from typing import Optional

from .base import BaseLLU
from .utils import (
    DEVICE,
    _activate,
    _ensure_3d,
    _small_init,
    _zero_out_last,
    _validate_parameterization,
)


class CrossAttnLoraLN(BaseLLU):
    """LoRA-style learned low-rank factors refined by cross-attention.

    Two factor matrices are learned parameters (``mat_o`` in the
    ``out_features`` space, ``mat_i`` in the ``in_features`` space):

    * ``lora`` mode: ``mat_o`` is the ``A`` factor and ``mat_i`` is the ``B``
      factor, so the adaptive path is ``((x @ mat_i^T) @ mat_o)``
      (equivalently ``x @ mat_i^T @ mat_o``).
    * ``svd`` mode: ``mat_o`` is ``U`` and ``mat_i`` is ``V``; a learned
      per-rank scale ``g`` modulates the diagonal, giving
      ``((x @ mat_i^T) * g) @ mat_o``.

    Both factors are refined by a cross-attention block that conditions them on
    the source sequence. Zero-initialised so the adaptive path contributes
    nothing at step 1 (output equals the core ``nn.Linear``).
    """

    def __init__(
        self,
        in_features: int,
        out_features: int,
        rank: int = 4,
        bias: bool = True,
        dynamic_bias: bool = False,
        factor_activation: str = "norm",
        scale_init: float = 0.01,
        normalize_input: bool = True,
        cond_dim: Optional[int] = None,
        init_method: str = "xavier",
        parameterization: str = "lora",
        lora_alpha: float = 1.0,
        attn_dim: int = 32,
        attn_heads: int = 2,
        attn_activation: str = "silu",
        device: Optional[torch.device] = None,
        dtype: torch.dtype = torch.float32,
    ) -> None:
        r"""__init__(in_features, out_features, rank=4, bias=True, dynamic_bias=False, factor_activation="norm", scale_init=0.01, normalize_input=True, cond_dim=None, init_method="xavier", parameterization="lora", attn_dim=32, attn_heads=2, attn_activation="gelu", device=None, dtype=torch.float32) -> None

        Args:
            in_features (int): size of each input sample.
            out_features (int): size of each output sample.
            rank (int): number of rank slots (``R``) in the two factor matrices.
                Default: ``4``.
            bias (bool): whether the core :class:`~nn.Linear` has a learnable bias.
                Default: ``True``.
            dynamic_bias (bool): if ``True``, an input-dependent bias from an MLP
                (driven by ``cond``) is added to the output. Default: ``False``.
            factor_activation (str): activation for the refined factor matrices.
                One of ``"tanh"``, ``"norm"``, ``"rmsnorm"``, or ``"none"``.
                Default: ``"norm"``.
            scale_init (float): retained for API symmetry with the other LLU
                variants (the adaptive path here has no standalone scalar scale).
                Default: ``0.01``.
            normalize_input (bool): if ``True``, apply RMSNorm to the
                conditioning tensor before it is projected into the attention
                space. Default: ``True``.
            cond_dim (int, optional): dimension of the conditioning tensor used
                as the cross-attention source. Defaults to ``in_features`` so
                that, when no separate ``cond`` is supplied, ``x`` is the source.
            init_method (str): weight initialisation method used for the factor
                matrices. One of ``"hyperfan_in"``, ``"hyperfan_out"``,
                ``"xavier"``, or ``"small"``. Default: ``"xavier"``.
            parameterization (str): parameterization mode, either ``"lora"`` or
                ``"svd"``. Default: ``"lora"``.
            attn_dim (int): hidden dimension of the cross-attention space. Must
                be divisible by ``attn_heads``. Default: ``32``.
            attn_heads (int): number of attention heads in the cross-attention
                block. Default: ``2``.
            attn_activation (str): non-linearity of the decoder feed-forward
                sublayer. One of ``"silu"``, ``"gelu"``.
                Default: ``"silu"``.
            device (torch.device, optional): the desired device of the
                parameters. Default: ``None``.
            dtype (torch.dtype): the desired data type of the parameters.
                Default: ``torch.float32``.
        """
        if rank < 1:
            raise ValueError(f"rank must be >= 1, got {rank}")
        _validate_parameterization(parameterization)

        super().__init__(
            in_features=in_features,
            out_features=out_features,
            bias=bias,
            scale_init=scale_init,
            factor_activation=factor_activation,
            init_method=init_method,
            device=device,
            dtype=dtype,
        )
        dev = device if device is not None else DEVICE

        self.rank = rank
        self.normalize_input = normalize_input
        self.cond_dim = cond_dim if cond_dim is not None else in_features
        self.parameterization = parameterization
        self.lora_alpha = lora_alpha

        # Make attn_dim divisible by attn_heads (and non-zero).
        attn_heads = max(1, int(attn_heads))
        attn_dim = max(attn_heads, int(attn_dim))
        attn_dim = (attn_dim // attn_heads) * attn_heads
        self.attn_dim = attn_dim
        self.attn_heads = attn_heads
        self.attn_activation = attn_activation

        # --- The two learned low-rank factor matrices (LoRA-style). ---
        # mat_o lives in the out_features space (A in lora, U in svd);
        # mat_i lives in the in_features space (B in lora, V in svd).
        self.mat_o = nn.Parameter(torch.empty(self.rank, out_features, device=dev, dtype=dtype))
        self.mat_i = nn.Parameter(torch.empty(self.rank, in_features, device=dev, dtype=dtype))

        # --- Cross-attention refiner. ---
        # Project the two factor matrices into the shared attention space to
        # form the target query tokens (split back after the decoder).
        self.w_qo = nn.Linear(out_features, attn_dim, bias=False, device=dev, dtype=dtype)
        self.w_qi = nn.Linear(in_features, attn_dim, bias=False, device=dev, dtype=dtype)
        # Project the source sequence (cond) into the attention space to form
        # the cross-attention keys and values.
        self.src_proj = nn.Linear(self.cond_dim, attn_dim, bias=False, device=dev, dtype=dtype)
        # Residual readouts back into each factor's native space. Zero-initialised
        # so they add nothing at step 1 (adaptive path stays zero).
        self.w_o = nn.Linear(attn_dim, out_features, bias=True, device=dev, dtype=dtype)
        self.w_i = nn.Linear(attn_dim, in_features, bias=True, device=dev, dtype=dtype)

        act = {"silu": nn.SiLU, "gelu": nn.GELU}[attn_activation]
        self.decoder = nn.TransformerDecoderLayer(
            d_model=attn_dim,
            nhead=attn_heads,
            dim_feedforward=max(attn_dim * 2, 16),
            activation=act(),
            batch_first=True,
            norm_first=True,
            dropout=0.0,
        )

        # --- SVD diagonal scale. ---
        # Learned per-rank scale (svd mode only). Initialised to ones so the
        # adaptive path is still zero at step 1 (because mat_i is zero) while
        # gradient flow into mat_i is preserved through this non-zero scale.
        if self.parameterization == "svd":
            self.g = nn.Parameter(torch.ones(self.rank, device=dev, dtype=dtype))
        else:
            self.g = None

        # --- Optional dynamic bias (driven by cond). ---
        hidden = max(self.cond_dim // 4, rank * 16)
        self.bias_dynamic: Optional[nn.Sequential] = (
            nn.Sequential(
                nn.Linear(self.cond_dim, hidden, device=dev, dtype=dtype),
                nn.SiLU(),
                nn.Linear(hidden, out_features, device=dev, dtype=dtype),
            )
            if dynamic_bias
            else None
        )

        self._init_weights()

    def _init_weights(self) -> None:
        r"""_init_weights() -> None

        Initialise the learned factors and the cross-attention refiner so that
        at step 1 the adaptive path is exactly zero:

        * ``mat_o`` (the ``A``/``U`` anchor) is a small non-zero init -- it
          carries the gradient that lets ``mat_i`` move at step 1.
        * ``mat_i`` (the ``B``/``V`` factor) is zeroed, forcing the adaptive
          output to zero at step 1 while still receiving gradient via
          ``mat_o``.
        * The residual readouts ``w_o``/``w_i`` are zeroed, so the cross-attention
          refinement adds nothing on the first forward.
        * ``g`` (svd) starts at ones: the adaptive path is zero because
          ``mat_i`` is zero, but the non-zero scale keeps gradient flowing into
          ``mat_i``'s refiner.
        * The dynamic-bias MLP is small-init with a zeroed final layer.
        """
        gain = {"hyperfan_in": 0.02, "hyperfan_out": 0.02, "small": 0.02}.get(self.init_method, 1.0)
        nn.init.xavier_uniform_(self.mat_o, gain=gain)
        nn.init.zeros_(self.mat_i)

        if self.parameterization == "svd" and self.g is not None:
            nn.init.ones_(self.g)

        with torch.no_grad():
            for proj in (self.w_o, self.w_i):
                nn.init.zeros_(proj.weight)
                if proj.bias is not None:
                    nn.init.zeros_(proj.bias)

        if self.bias_dynamic is not None:
            _small_init(self.bias_dynamic)
            _zero_out_last(self.bias_dynamic)

    def forward(
        self,
        x: torch.Tensor,
        cond: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:
        r"""forward(x, cond=None) -> Tensor

        Args:
            x (Tensor): input tensor of shape ``(..., in_features)``. The last
                dimension is the feature axis; the penultimate dimension (if
                present) is the sequence axis that the cross-attention source
                attends over.
            cond (Tensor, optional): the cross-attention source (keys/values).
                When ``None``, ``x`` is used. May have a different feature
                dimension (``cond_dim``) from ``x``; it is projected into the
                attention space internally.

        Returns:
            Tensor: output tensor of shape ``(..., out_features)``.
        """
        in_shape = x.shape
        x3d, _ = _ensure_3d(x)
        Bf, T, feat_in = x3d.shape

        c = cond if cond is not None else x
        c3d, _ = _ensure_3d(c)
        Bf_c, Tc, C = c3d.shape
        Bf = max(Bf, Bf_c)
        if Bf_c == 1 and Bf > 1:
            c3d = c3d.expand(Bf, -1, -1)

        if self.normalize_input:
            c_norm = F.rms_norm(c3d, (C,))
        else:
            c_norm = c3d

        # Source sequence -> attention space (keys + values).
        mem = self.src_proj(c_norm)  # (Bf, Tc, D)

        # Factor matrices -> target query tokens in the attention space.
        q_o = self.w_qo(self.mat_o)  # (R, D)
        q_i = self.w_qi(self.mat_i)  # (R, D)
        tgt = torch.cat([q_o, q_i], dim=0).unsqueeze(0).expand(Bf, -1, -1)  # (Bf, 2R, D)

        out = self.decoder(tgt, mem)  # (Bf, 2R, D)
        o_ref = self.w_o(out[:, : self.rank, :])  # (Bf, R, O)
        i_ref = self.w_i(out[:, self.rank :, :])  # (Bf, R, I)

        mat_o_p = self.mat_o.unsqueeze(0) + o_ref  # (Bf, R, O)
        mat_i_p = self.mat_i.unsqueeze(0) + i_ref  # (Bf, R, I)

        a = _activate(mat_o_p, self.factor_activation)
        b = _activate(mat_i_p, self.factor_activation)

        if self.parameterization == "lora":
            dot = torch.einsum("bri,bti->btr", b, x3d)  # (Bf, T, R)
            adaptive3d = torch.einsum("btr,bro->bto", dot, a)  # (Bf, T, O)
        else:
            v = torch.einsum("bti,bri->btr", x3d, b)  # (Bf, T, R)
            adaptive3d = torch.einsum("btr,r,bro->bto", v, self.g, a)  # (Bf, T, O)

        lora_scale = self.lora_alpha / self.rank

        out3d = self.linear_core(x3d) + lora_scale * adaptive3d

        if self.bias_dynamic is not None:
            bias3d = self.bias_dynamic(c_norm)[:, :T, :]
            out3d = out3d + bias3d

        return out3d.reshape(*in_shape[:-1], self.out_features)

    def extra_repr(self) -> str:
        return (
            f"in={self.in_features}, out={self.out_features}, rank={self.rank}, "
            f"act={self.factor_activation}, norm_input={self.normalize_input}, "
            f"attn_dim={self.attn_dim}, attn_heads={self.attn_heads}, "
            f"mode={self.parameterization}, lora_alpha={self.lora_alpha}"
        )
